name: Tests

on:
    push: ~
    pull_request: ~

jobs:
    phpcs:
        name: PHPCS
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.2
                  extensions: curl, mbstring
                  coverage: none
                  tools: composer:v2, cs2pr

            - run: composer update --no-progress

            - run: vendor/bin/phpcs -q --report=checkstyle | cs2pr

    phpunit:
        name: PHPUnit on ${{ matrix.php }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ["7.2", "7.3", "7.4"]
                coverage: [true]
                composer-flags: [""]

        steps:
            - uses: actions/checkout@v2

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: curl, mbstring
                  coverage: pcov
                  tools: composer:v2

            - run: composer update --no-progress

            - run: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

            - run: bash <(curl -s https://codecov.io/bash) -f coverage.clover

    phpstan:
        name: PHPStan
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.2
                  extensions: curl, mbstring
                  coverage: none
                  tools: composer:v2

            - run: composer update --no-progress

            - run: vendor/bin/phpstan analyse

    psalm:
        name: Psalm
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.2
                  extensions: curl, mbstring
                  coverage: none
                  tools: composer:v2

            - run: composer update --no-progress

            - run: vendor/bin/psalm
